#!/bin/bash
# File  : issstatus.sh
#
# This script fetch the ISS statuses from the TFL API
# http://api.open-notify.org/astros.json and returns the results in terminal.
#

if ! command -v jq &>/dev/null; then
  echo "You need to install jq to run this script."
  echo "https://github.com/stedolan/jq"
  echo
  case "$OSTYPE" in
  solaris*)
    echo "pkgutil -i jq"
    ;;
  darwin*)
    echo "brew install jq"
    ;;
  linux*)
    echo "Debian/Ubuntu  sudo apt-get install jq"
    echo "Fedora         sudo dnf install jq"
    echo "openSUSE       sudo zipper install jq"
    echo "Arch           sudo pacman -Sy jq"
    ;;
  bsd*)
    echo "pkg install jq"
    ;;
  msys*)
    echo "chocolatey install jq"
    ;;
  *)
    echo "https://stedolan.github.io/jq/download/"
    ;;
  esac
  exit 0
fi

LINE_SEARCH=$1
DELIMITER="¬"
NONE="\033[0m"
URL="http://api.open-notify.org/astros.json"

curl -s $URL > tttt

cat tttt |  jq  ' .number'

cat tttt |
     jq '.[] |
         .[] |
         .name' 2> /dev/null |
         sed 's/"//g'

rm tttt
